version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image
    slack: circleci/slack@0.1.10

executors:
    default:
        docker:
            - image: circleci/node

jobs:
    send-slack-notify:
        executor: default
        steps:
            - slack/notify:
                message: |
                    Test message from Slack.
                        https://circleci.com/gh/kenfj/circleci-orb101/${CIRCLE_BUILD_NUM}

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - send-slack-notify:
                requires:
                    - hello/hello-build
